### ISSUE TITLE
如何将别人的镜像转移到自己的仓库

### ISSUE THREAD

**Issue by 2018song** [mebusy/notes#2]
观看了您的文章，作为一个小白实在是不懂程序，但是需要那个镜像部署，但怕作者会将镜像删除，因此想复制到自己的账号下，求大神解决办法

**Comment by mebusy** [comment]
抱歉 一直没看到这个 issue. 这个需求的话，先把镜像拉到本地，然后push到自己的仓库就可以了。
官网有个push到本地仓库的文档, 大致都差不多的: https://docs.docker.com/registry/
