### ISSUE TITLE
请问如何理解pdf*delta 近似pmf呢？

### ISSUE THREAD

**Issue by BeBraveBeCurious** [mebusy/notes#4]
感谢博主笔记，非常有用。
想请问一下# 如何理解pdf*delta 近似pmf呢？
感觉比较直观的是sum(pdf * delta x) = cdf, 对pdf和pmf的直接理解感觉不是很清楚，谢谢博主~

**Comment by mebusy** [comment]
得到了pdf， 下一步应该是求积分计算期望值。
自己不想算积分,偷懒了。 
我是把连续的随机变量 近似成了 以 delta 为单位的离散的情况. 这里delta =  1000.0/100000 = 0.01
pdf * delta 就是那一堆的离散的概率，对 `pdf * delta` 求和结果是个常数≈1.   
cdf 是一个函数。
